### ISSUE TITLE
When will be the models and code available ?

### ISSUE THREAD

**Issue by Mahmood-Hussain** [yangxy/SDL#1]
Thanks for the nice work!
Do you have plans to release the code and pre-trained models soon?

**Comment by yangxy** [comment]
Thanks for your interest.  The source codes will be released next week. Please stay tuned.

**Comment by Mahmood-Hussain** [comment]
Thank you so much for a quick reply!

**Comment by delldu** [comment]
We are looking forward, come on, please !!!

**Comment by yangxy** [comment]
Sorry for the delay. I am still working on it. Will be released very soon.
