### ISSUE TITLE
How to run on single GPU?

### ISSUE THREAD

**Issue by Trainmaster9977** [yangxy/SDL#2]
Trying to run this on single GPU, and I'm having trouble figuring out what I should change in the train command to do so.

**Comment by yangxy** [comment]
Try ```CUDA_VISIBLE_DEVICES=0 python train.py -opt options/train_SDL_VFI.yml --auto_resume```.

**Comment by yangxy** [comment]
And change the value of ```num_gpu``` to 1 or auto
https://github.com/yangxy/SDL/blob/7a1f39c9e23396642765b6036ec00a9d454fa5ab/options/train_SDL_VFI.yml#L4
